/*
 * generated by Xtext 2.30.0
 */
package uk.ac.kcl.inf.mdd.tracerypp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TraceryPPAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/kcl/inf/mdd/tracerypp/parser/antlr/internal/InternalTraceryPP.tokens");
	}
}
