/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mdd.tracerypp.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.mdd.tracerypp.ui.internal.TraceryppActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TraceryPPExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TraceryppActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TraceryppActivator activator = TraceryppActivator.getInstance();
		return activator != null ? activator.getInjector(TraceryppActivator.UK_AC_KCL_INF_MDD_TRACERYPP_TRACERYPP) : null;
	}

}
