/*
 * generated by Xtext 2.30.0
 */
package tracerypp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTraceryPlusPlusValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(tracerypp.traceryPlusPlus.TraceryPlusPlusPackage.eINSTANCE);
		return result;
	}
}
