/**
 * generated by Xtext 2.30.0
 */
package tracerypp.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TraceryPlusPlusIdeModule extends AbstractTraceryPlusPlusIdeModule {
}
