/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mdd.tracerypp.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TraceryPPGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStatementsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStatementsStatementParserRuleCall_0_0 = (RuleCall)cStatementsAssignment_0.eContents().get(0);
		private final Assignment cStoryAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStoryStoryParserRuleCall_1_0 = (RuleCall)cStoryAssignment_1.eContents().get(0);
		
		//// Version 1.0
		//Model:
		//    statements += Statement*
		//    story = Story
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//statements += Statement*
		//story = Story
		public Group getGroup() { return cGroup; }
		
		//statements += Statement*
		public Assignment getStatementsAssignment_0() { return cStatementsAssignment_0; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_0_0() { return cStatementsStatementParserRuleCall_0_0; }
		
		//story = Story
		public Assignment getStoryAssignment_1() { return cStoryAssignment_1; }
		
		//Story
		public RuleCall getStoryStoryParserRuleCall_1_0() { return cStoryStoryParserRuleCall_1_0; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Statement");
		private final RuleCall cDeclarationParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Statement:
		//    Declaration
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Declaration
		public RuleCall getDeclarationParserRuleCall() { return cDeclarationParserRuleCall; }
	}
	public class DeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Declaration");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cListDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cObjectDeclarationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Declaration:
		//    ListDeclaration |
		//    ObjectDeclaration
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ListDeclaration |
		//ObjectDeclaration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ListDeclaration
		public RuleCall getListDeclarationParserRuleCall_0() { return cListDeclarationParserRuleCall_0; }
		
		//ObjectDeclaration
		public RuleCall getObjectDeclarationParserRuleCall_1() { return cObjectDeclarationParserRuleCall_1; }
	}
	public class StoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Story");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStoryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTheStoryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStoryAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cStoryAlternatives_2_0 = (Alternatives)cStoryAssignment_2.eContents().get(0);
		private final RuleCall cStoryWordParserRuleCall_2_0_0 = (RuleCall)cStoryAlternatives_2_0.eContents().get(0);
		private final RuleCall cStoryStoryVariableParserRuleCall_2_0_1 = (RuleCall)cStoryAlternatives_2_0.eContents().get(1);
		private final RuleCall cStoryObjectAttributeParserRuleCall_2_0_2 = (RuleCall)cStoryAlternatives_2_0.eContents().get(2);
		
		///*
		//    Used to define what the story should look like.
		//    There must be only one story in the model for now.
		// */
		//Story:
		//    {Story} "The story:"
		//    story += ( Word | StoryVariable | ObjectAttribute )*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Story} "The story:"
		//story += ( Word | StoryVariable | ObjectAttribute )*
		public Group getGroup() { return cGroup; }
		
		//{Story}
		public Action getStoryAction_0() { return cStoryAction_0; }
		
		//"The story:"
		public Keyword getTheStoryKeyword_1() { return cTheStoryKeyword_1; }
		
		//story += ( Word | StoryVariable | ObjectAttribute )*
		public Assignment getStoryAssignment_2() { return cStoryAssignment_2; }
		
		//( Word | StoryVariable | ObjectAttribute )
		public Alternatives getStoryAlternatives_2_0() { return cStoryAlternatives_2_0; }
		
		//Word
		public RuleCall getStoryWordParserRuleCall_2_0_0() { return cStoryWordParserRuleCall_2_0_0; }
		
		//StoryVariable
		public RuleCall getStoryStoryVariableParserRuleCall_2_0_1() { return cStoryStoryVariableParserRuleCall_2_0_1; }
		
		//ObjectAttribute
		public RuleCall getStoryObjectAttributeParserRuleCall_2_0_2() { return cStoryObjectAttributeParserRuleCall_2_0_2; }
	}
	public class ListDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.ListDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStart_symbolAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cStart_symbolVariableParserRuleCall_0_0 = (RuleCall)cStart_symbolAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cCanHaveValuesKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cCanBeKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cListAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cListWordListParserRuleCall_2_0 = (RuleCall)cListAssignment_2.eContents().get(0);
		
		///*
		//    Define a variable and give that variable a list of values it can take.
		//    Examples of use:
		//        colors can have values: green, blue, orange
		//        fruit can be: banana or apple or pear
		// */
		//ListDeclaration:
		//    start_symbol = Variable  ("can have values:" | "can be:") list = WordList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//start_symbol = Variable  ("can have values:" | "can be:") list = WordList
		public Group getGroup() { return cGroup; }
		
		//start_symbol = Variable
		public Assignment getStart_symbolAssignment_0() { return cStart_symbolAssignment_0; }
		
		//Variable
		public RuleCall getStart_symbolVariableParserRuleCall_0_0() { return cStart_symbolVariableParserRuleCall_0_0; }
		
		//("can have values:" | "can be:")
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"can have values:"
		public Keyword getCanHaveValuesKeyword_1_0() { return cCanHaveValuesKeyword_1_0; }
		
		//"can be:"
		public Keyword getCanBeKeyword_1_1() { return cCanBeKeyword_1_1; }
		
		//list = WordList
		public Assignment getListAssignment_2() { return cListAssignment_2; }
		
		//WordList
		public RuleCall getListWordListParserRuleCall_2_0() { return cListWordListParserRuleCall_2_0; }
	}
	public class ObjectDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.ObjectDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cIsAnObjectKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cItHasTheseAttributesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttributesAttributeListParserRuleCall_3_0 = (RuleCall)cAttributesAssignment_3.eContents().get(0);
		
		//ObjectDeclaration:
		//    name = ID "is an object."
		//    "It has these attributes:" attributes = AttributeList
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name = ID "is an object."
		//"It has these attributes:" attributes = AttributeList
		public Group getGroup() { return cGroup; }
		
		//name = ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//"is an object."
		public Keyword getIsAnObjectKeyword_1() { return cIsAnObjectKeyword_1; }
		
		//"It has these attributes:"
		public Keyword getItHasTheseAttributesKeyword_2() { return cItHasTheseAttributesKeyword_2; }
		
		//attributes = AttributeList
		public Assignment getAttributesAssignment_3() { return cAttributesAssignment_3; }
		
		//AttributeList
		public RuleCall getAttributesAttributeListParserRuleCall_3_0() { return cAttributesAttributeListParserRuleCall_3_0; }
	}
	public class WordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Word");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		///*
		//    Basic building blocks
		// */
		//Word:
		//    value = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value = STRING
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Variable");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Variable:
		//    name = ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name = ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class StoryVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.StoryVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVariableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cVariableVariableCrossReference_0_0 = (CrossReference)cVariableAssignment_0.eContents().get(0);
		private final RuleCall cVariableVariableIDTerminalRuleCall_0_0_1 = (RuleCall)cVariableVariableCrossReference_0_0.eContents().get(1);
		private final Assignment cModifiersAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cModifiersModifierParserRuleCall_1_0 = (RuleCall)cModifiersAssignment_1.eContents().get(0);
		
		//StoryVariable:
		//    variable = [Variable]
		//    modifiers += Modifier*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//variable = [Variable]
		//modifiers += Modifier*
		public Group getGroup() { return cGroup; }
		
		//variable = [Variable]
		public Assignment getVariableAssignment_0() { return cVariableAssignment_0; }
		
		//[Variable]
		public CrossReference getVariableVariableCrossReference_0_0() { return cVariableVariableCrossReference_0_0; }
		
		//ID
		public RuleCall getVariableVariableIDTerminalRuleCall_0_0_1() { return cVariableVariableIDTerminalRuleCall_0_0_1; }
		
		//modifiers += Modifier*
		public Assignment getModifiersAssignment_1() { return cModifiersAssignment_1; }
		
		//Modifier
		public RuleCall getModifiersModifierParserRuleCall_1_0() { return cModifiersModifierParserRuleCall_1_0; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Attribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cValueAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_2_0 = (RuleCall)cValueAssignment_1_2.eContents().get(0);
		
		//Attribute:
		//    name = ID |
		//    name = ID "=" value = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name = ID |
		//name = ID "=" value = STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//name = ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//name = ID "=" value = STRING
		public Group getGroup_1() { return cGroup_1; }
		
		//name = ID
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0_0() { return cNameIDTerminalRuleCall_1_0_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_1_1() { return cEqualsSignKeyword_1_1; }
		
		//value = STRING
		public Assignment getValueAssignment_1_2() { return cValueAssignment_1_2; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_2_0() { return cValueSTRINGTerminalRuleCall_1_2_0; }
	}
	public class ObjectAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.ObjectAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cObjectAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cObjectObjectDeclarationCrossReference_0_0 = (CrossReference)cObjectAssignment_0.eContents().get(0);
		private final RuleCall cObjectObjectDeclarationIDTerminalRuleCall_0_0_1 = (RuleCall)cObjectObjectDeclarationCrossReference_0_0.eContents().get(1);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAttributeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAttributeIDTerminalRuleCall_2_0 = (RuleCall)cAttributeAssignment_2.eContents().get(0);
		
		//ObjectAttribute:
		//    object = [ObjectDeclaration] "." attribute = ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//object = [ObjectDeclaration] "." attribute = ID
		public Group getGroup() { return cGroup; }
		
		//object = [ObjectDeclaration]
		public Assignment getObjectAssignment_0() { return cObjectAssignment_0; }
		
		//[ObjectDeclaration]
		public CrossReference getObjectObjectDeclarationCrossReference_0_0() { return cObjectObjectDeclarationCrossReference_0_0; }
		
		//ID
		public RuleCall getObjectObjectDeclarationIDTerminalRuleCall_0_0_1() { return cObjectObjectDeclarationIDTerminalRuleCall_0_0_1; }
		
		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//attribute = ID
		public Assignment getAttributeAssignment_2() { return cAttributeAssignment_2; }
		
		//ID
		public RuleCall getAttributeIDTerminalRuleCall_2_0() { return cAttributeIDTerminalRuleCall_2_0; }
	}
	public class WordListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.WordList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cWordsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cWordsWordParserRuleCall_0_0 = (RuleCall)cWordsAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cSeparatorParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cWordsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cWordsWordParserRuleCall_1_1_0 = (RuleCall)cWordsAssignment_1_1.eContents().get(0);
		
		//WordList:
		//    words += Word (Separator + words += Word)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//words += Word (Separator + words += Word)*
		public Group getGroup() { return cGroup; }
		
		//words += Word
		public Assignment getWordsAssignment_0() { return cWordsAssignment_0; }
		
		//Word
		public RuleCall getWordsWordParserRuleCall_0_0() { return cWordsWordParserRuleCall_0_0; }
		
		//(Separator + words += Word)*
		public Group getGroup_1() { return cGroup_1; }
		
		//Separator +
		public RuleCall getSeparatorParserRuleCall_1_0() { return cSeparatorParserRuleCall_1_0; }
		
		//words += Word
		public Assignment getWordsAssignment_1_1() { return cWordsAssignment_1_1; }
		
		//Word
		public RuleCall getWordsWordParserRuleCall_1_1_0() { return cWordsWordParserRuleCall_1_1_0; }
	}
	public class AttributeListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.AttributeList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAttributesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAttributesAttributeParserRuleCall_0_0 = (RuleCall)cAttributesAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAttributesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_1_1_0 = (RuleCall)cAttributesAssignment_1_1.eContents().get(0);
		
		//AttributeList:
		//    attributes += Attribute (',' + attributes += Attribute)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//attributes += Attribute (',' + attributes += Attribute)*
		public Group getGroup() { return cGroup; }
		
		//attributes += Attribute
		public Assignment getAttributesAssignment_0() { return cAttributesAssignment_0; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_0_0() { return cAttributesAttributeParserRuleCall_0_0; }
		
		//(',' + attributes += Attribute)*
		public Group getGroup_1() { return cGroup_1; }
		
		//',' +
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//attributes += Attribute
		public Assignment getAttributesAssignment_1_1() { return cAttributesAssignment_1_1; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_1_1_0() { return cAttributesAttributeParserRuleCall_1_1_0; }
	}
	public class SeparatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Separator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cCommaKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cOrKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Separator:
		//    "," | "or"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"," | "or"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//","
		public Keyword getCommaKeyword_0() { return cCommaKeyword_0; }
		
		//"or"
		public Keyword getOrKeyword_1() { return cOrKeyword_1; }
	}
	public class ModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.Modifier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCapitalizationModifierParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFullCapitalizationModifierParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPluralityModifierParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cArticleModifierParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPastTenseModifierParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Modifier:
		//    CapitalizationModifier |
		//    FullCapitalizationModifier |
		//    PluralityModifier |
		//    ArticleModifier |
		//    PastTenseModifier
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//CapitalizationModifier |
		//FullCapitalizationModifier |
		//PluralityModifier |
		//ArticleModifier |
		//PastTenseModifier
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CapitalizationModifier
		public RuleCall getCapitalizationModifierParserRuleCall_0() { return cCapitalizationModifierParserRuleCall_0; }
		
		//FullCapitalizationModifier
		public RuleCall getFullCapitalizationModifierParserRuleCall_1() { return cFullCapitalizationModifierParserRuleCall_1; }
		
		//PluralityModifier
		public RuleCall getPluralityModifierParserRuleCall_2() { return cPluralityModifierParserRuleCall_2; }
		
		//ArticleModifier
		public RuleCall getArticleModifierParserRuleCall_3() { return cArticleModifierParserRuleCall_3; }
		
		//PastTenseModifier
		public RuleCall getPastTenseModifierParserRuleCall_4() { return cPastTenseModifierParserRuleCall_4; }
	}
	public class CapitalizationModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.CapitalizationModifier");
		private final Keyword cCapitalizeKeyword = (Keyword)rule.eContents().get(1);
		
		//CapitalizationModifier:
		//    ".capitalize"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//".capitalize"
		public Keyword getCapitalizeKeyword() { return cCapitalizeKeyword; }
	}
	public class FullCapitalizationModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.FullCapitalizationModifier");
		private final Keyword cCAPITALIZEKeyword = (Keyword)rule.eContents().get(1);
		
		//FullCapitalizationModifier:
		//    ".CAPITALIZE"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//".CAPITALIZE"
		public Keyword getCAPITALIZEKeyword() { return cCAPITALIZEKeyword; }
	}
	public class PluralityModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.PluralityModifier");
		private final Keyword cSKeyword = (Keyword)rule.eContents().get(1);
		
		//PluralityModifier:
		//    ".s"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//".s"
		public Keyword getSKeyword() { return cSKeyword; }
	}
	public class ArticleModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.ArticleModifier");
		private final Keyword cAKeyword = (Keyword)rule.eContents().get(1);
		
		//ArticleModifier:
		//    ".a"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//".a"
		public Keyword getAKeyword() { return cAKeyword; }
	}
	public class PastTenseModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.mdd.tracerypp.TraceryPP.PastTenseModifier");
		private final Keyword cEdKeyword = (Keyword)rule.eContents().get(1);
		
		//PastTenseModifier:
		//    ".ed"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//".ed"
		public Keyword getEdKeyword() { return cEdKeyword; }
	}
	
	
	private final ModelElements pModel;
	private final StatementElements pStatement;
	private final DeclarationElements pDeclaration;
	private final StoryElements pStory;
	private final ListDeclarationElements pListDeclaration;
	private final ObjectDeclarationElements pObjectDeclaration;
	private final WordElements pWord;
	private final VariableElements pVariable;
	private final StoryVariableElements pStoryVariable;
	private final AttributeElements pAttribute;
	private final ObjectAttributeElements pObjectAttribute;
	private final WordListElements pWordList;
	private final AttributeListElements pAttributeList;
	private final SeparatorElements pSeparator;
	private final ModifierElements pModifier;
	private final CapitalizationModifierElements pCapitalizationModifier;
	private final FullCapitalizationModifierElements pFullCapitalizationModifier;
	private final PluralityModifierElements pPluralityModifier;
	private final ArticleModifierElements pArticleModifier;
	private final PastTenseModifierElements pPastTenseModifier;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TraceryPPGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pStatement = new StatementElements();
		this.pDeclaration = new DeclarationElements();
		this.pStory = new StoryElements();
		this.pListDeclaration = new ListDeclarationElements();
		this.pObjectDeclaration = new ObjectDeclarationElements();
		this.pWord = new WordElements();
		this.pVariable = new VariableElements();
		this.pStoryVariable = new StoryVariableElements();
		this.pAttribute = new AttributeElements();
		this.pObjectAttribute = new ObjectAttributeElements();
		this.pWordList = new WordListElements();
		this.pAttributeList = new AttributeListElements();
		this.pSeparator = new SeparatorElements();
		this.pModifier = new ModifierElements();
		this.pCapitalizationModifier = new CapitalizationModifierElements();
		this.pFullCapitalizationModifier = new FullCapitalizationModifierElements();
		this.pPluralityModifier = new PluralityModifierElements();
		this.pArticleModifier = new ArticleModifierElements();
		this.pPastTenseModifier = new PastTenseModifierElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uk.ac.kcl.inf.mdd.tracerypp.TraceryPP".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// Version 1.0
	//Model:
	//    statements += Statement*
	//    story = Story
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Statement:
	//    Declaration
	//;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Declaration:
	//    ListDeclaration |
	//    ObjectDeclaration
	//;
	public DeclarationElements getDeclarationAccess() {
		return pDeclaration;
	}
	
	public ParserRule getDeclarationRule() {
		return getDeclarationAccess().getRule();
	}
	
	///*
	//    Used to define what the story should look like.
	//    There must be only one story in the model for now.
	// */
	//Story:
	//    {Story} "The story:"
	//    story += ( Word | StoryVariable | ObjectAttribute )*
	//;
	public StoryElements getStoryAccess() {
		return pStory;
	}
	
	public ParserRule getStoryRule() {
		return getStoryAccess().getRule();
	}
	
	///*
	//    Define a variable and give that variable a list of values it can take.
	//    Examples of use:
	//        colors can have values: green, blue, orange
	//        fruit can be: banana or apple or pear
	// */
	//ListDeclaration:
	//    start_symbol = Variable  ("can have values:" | "can be:") list = WordList
	//;
	public ListDeclarationElements getListDeclarationAccess() {
		return pListDeclaration;
	}
	
	public ParserRule getListDeclarationRule() {
		return getListDeclarationAccess().getRule();
	}
	
	//ObjectDeclaration:
	//    name = ID "is an object."
	//    "It has these attributes:" attributes = AttributeList
	//;
	public ObjectDeclarationElements getObjectDeclarationAccess() {
		return pObjectDeclaration;
	}
	
	public ParserRule getObjectDeclarationRule() {
		return getObjectDeclarationAccess().getRule();
	}
	
	///*
	//    Basic building blocks
	// */
	//Word:
	//    value = STRING
	//;
	public WordElements getWordAccess() {
		return pWord;
	}
	
	public ParserRule getWordRule() {
		return getWordAccess().getRule();
	}
	
	//Variable:
	//    name = ID
	//;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//StoryVariable:
	//    variable = [Variable]
	//    modifiers += Modifier*
	//;
	public StoryVariableElements getStoryVariableAccess() {
		return pStoryVariable;
	}
	
	public ParserRule getStoryVariableRule() {
		return getStoryVariableAccess().getRule();
	}
	
	//Attribute:
	//    name = ID |
	//    name = ID "=" value = STRING
	//;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//ObjectAttribute:
	//    object = [ObjectDeclaration] "." attribute = ID
	//;
	public ObjectAttributeElements getObjectAttributeAccess() {
		return pObjectAttribute;
	}
	
	public ParserRule getObjectAttributeRule() {
		return getObjectAttributeAccess().getRule();
	}
	
	//WordList:
	//    words += Word (Separator + words += Word)*
	//;
	public WordListElements getWordListAccess() {
		return pWordList;
	}
	
	public ParserRule getWordListRule() {
		return getWordListAccess().getRule();
	}
	
	//AttributeList:
	//    attributes += Attribute (',' + attributes += Attribute)*
	//;
	public AttributeListElements getAttributeListAccess() {
		return pAttributeList;
	}
	
	public ParserRule getAttributeListRule() {
		return getAttributeListAccess().getRule();
	}
	
	//Separator:
	//    "," | "or"
	//;
	public SeparatorElements getSeparatorAccess() {
		return pSeparator;
	}
	
	public ParserRule getSeparatorRule() {
		return getSeparatorAccess().getRule();
	}
	
	//Modifier:
	//    CapitalizationModifier |
	//    FullCapitalizationModifier |
	//    PluralityModifier |
	//    ArticleModifier |
	//    PastTenseModifier
	//;
	public ModifierElements getModifierAccess() {
		return pModifier;
	}
	
	public ParserRule getModifierRule() {
		return getModifierAccess().getRule();
	}
	
	//CapitalizationModifier:
	//    ".capitalize"
	//;
	public CapitalizationModifierElements getCapitalizationModifierAccess() {
		return pCapitalizationModifier;
	}
	
	public ParserRule getCapitalizationModifierRule() {
		return getCapitalizationModifierAccess().getRule();
	}
	
	//FullCapitalizationModifier:
	//    ".CAPITALIZE"
	//;
	public FullCapitalizationModifierElements getFullCapitalizationModifierAccess() {
		return pFullCapitalizationModifier;
	}
	
	public ParserRule getFullCapitalizationModifierRule() {
		return getFullCapitalizationModifierAccess().getRule();
	}
	
	//PluralityModifier:
	//    ".s"
	//;
	public PluralityModifierElements getPluralityModifierAccess() {
		return pPluralityModifier;
	}
	
	public ParserRule getPluralityModifierRule() {
		return getPluralityModifierAccess().getRule();
	}
	
	//ArticleModifier:
	//    ".a"
	//;
	public ArticleModifierElements getArticleModifierAccess() {
		return pArticleModifier;
	}
	
	public ParserRule getArticleModifierRule() {
		return getArticleModifierAccess().getRule();
	}
	
	//PastTenseModifier:
	//    ".ed"
	//;
	public PastTenseModifierElements getPastTenseModifierAccess() {
		return pPastTenseModifier;
	}
	
	public ParserRule getPastTenseModifierRule() {
		return getPastTenseModifierAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
