/*
 * generated by Xtext 2.30.0
 */
package tracerypp.validation

import org.eclipse.xtext.validation.Check
import tracerypp.traceryPlusPlus.ObjectDeclaration
import tracerypp.traceryPlusPlus.Attribute
import tracerypp.traceryPlusPlus.NameExistingListAttribute
import tracerypp.traceryPlusPlus.NameValueAttribute
import tracerypp.traceryPlusPlus.ListDeclaration

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TraceryPlusPlusValidator extends AbstractTraceryPlusPlusValidator {

	@Check
	def checkUniqueObjectName(ObjectDeclaration object) {
	   val objectName = object.name
	   val model = object.eContainer().eContents.filter(ObjectDeclaration).toList
	   var count = 0
	   for (obj : model) {
	   	if (obj.name == objectName) {
	   		count += 1;
	   	}
	   }
	   if (count > 1) {
	      error("Object with name '" + objectName + "' already exists.", null)
	   }
	}
	
	@Check
	def checkUniqueListName(ListDeclaration list) {
	   val listName = list.name
	   val model = list.eContainer().eContents.filter(ListDeclaration).toList
	   var count = 0
	   for (obj : model) {
	   	if (obj.name == listName) {
	   		count += 1;
	   	}
	   }
	   if (count > 1) {
	      error("List with name '" + listName + "' already exists.", null)
	   }
	}
	
	@Check
	def checkUniqueObjectAttribute(ObjectDeclaration object) {
	   val objectAttributes = object.attributes.attributes
	   
	   for (var i = 0; i < objectAttributes.size; i++) {
	      for (var j = i + 1; j < objectAttributes.size; j++) {
	         if (getAttributeName(objectAttributes.get(i)) == getAttributeName(objectAttributes.get(j))) {
	            error("Attribute '" + getAttributeName(objectAttributes.get(i)) + "' is used more than once.", null)
	         }
	      }
	   }
	   
	}
	
	def getAttributeName(Attribute attribute) {
    	if(attribute instanceof NameExistingListAttribute) {
    		return attribute.name
    	}
    	else if(attribute instanceof NameValueAttribute) {
    		return attribute.name
    	}
//    	else if(attribute instanceof JustNameAttribute) {
//    		return attribute.name.name
//    	}
	}
	
}
