/*
 * generated by Xtext 2.30.0
 */
package uk.ac.kcl.inf.mdd.tracerypp.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.mdd.tracerypp.ui.internal.TraceryppActivator;

public class TraceryPPUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TraceryppActivator.getInstance().getInjector("uk.ac.kcl.inf.mdd.tracerypp.TraceryPP");
	}

}
