/*
 * generated by Xtext 2.30.0
 */
package tracerypp.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TraceryPlusPlusUiModule extends AbstractTraceryPlusPlusUiModule {
}
