/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mdd.tracerypp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.mdd.tracerypp.TraceryPPRuntimeModule;
import uk.ac.kcl.inf.mdd.tracerypp.TraceryPPStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TraceryPPIdeSetup extends TraceryPPStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TraceryPPRuntimeModule(), new TraceryPPIdeModule()));
	}
	
}
