/*
 * generated by Xtext 2.30.0
 */
package tracerypp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TraceryPlusPlusAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tracerypp/parser/antlr/internal/InternalTraceryPlusPlus.tokens");
	}
}
