/**
 * generated by Xtext 2.30.0
 */
package tracerypp.traceryPlusPlus;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
} // Attribute
