/**
 * generated by Xtext 2.30.0
 */
package tracerypp.traceryPlusPlus;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tracerypp.traceryPlusPlus.AttributeList#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getAttributeList()
 * @model
 * @generated
 */
public interface AttributeList extends EObject
{
  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link tracerypp.traceryPlusPlus.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getAttributeList_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // AttributeList
