/**
 * generated by Xtext 2.30.0
 */
package tracerypp.traceryPlusPlus;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tracerypp.traceryPlusPlus.ListDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link tracerypp.traceryPlusPlus.ListDeclaration#getList <em>List</em>}</li>
 * </ul>
 *
 * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getListDeclaration()
 * @model
 * @generated
 */
public interface ListDeclaration extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Variable)
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getListDeclaration_Name()
   * @model containment="true"
   * @generated
   */
  Variable getName();

  /**
   * Sets the value of the '{@link tracerypp.traceryPlusPlus.ListDeclaration#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Variable value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(WordList)
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getListDeclaration_List()
   * @model containment="true"
   * @generated
   */
  WordList getList();

  /**
   * Sets the value of the '{@link tracerypp.traceryPlusPlus.ListDeclaration#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(WordList value);

} // ListDeclaration
