/**
 * generated by Xtext 2.30.0
 */
package tracerypp.traceryPlusPlus;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tracerypp.traceryPlusPlus.Model#getStatements <em>Statements</em>}</li>
 *   <li>{@link tracerypp.traceryPlusPlus.Model#getStory <em>Story</em>}</li>
 * </ul>
 *
 * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link tracerypp.traceryPlusPlus.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getModel_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

  /**
   * Returns the value of the '<em><b>Story</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Story</em>' containment reference.
   * @see #setStory(Story)
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getModel_Story()
   * @model containment="true"
   * @generated
   */
  Story getStory();

  /**
   * Sets the value of the '{@link tracerypp.traceryPlusPlus.Model#getStory <em>Story</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Story</em>' containment reference.
   * @see #getStory()
   * @generated
   */
  void setStory(Story value);

} // Model
