/**
 * generated by Xtext 2.30.0
 */
package tracerypp.traceryPlusPlus;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tracerypp.traceryPlusPlus.ObjectAttribute#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link tracerypp.traceryPlusPlus.ObjectAttribute#getModifiers <em>Modifiers</em>}</li>
 * </ul>
 *
 * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getObjectAttribute()
 * @model
 * @generated
 */
public interface ObjectAttribute extends ObjectUse
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getObjectAttribute_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link tracerypp.traceryPlusPlus.ObjectAttribute#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Modifiers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifiers</em>' containment reference.
   * @see #setModifiers(ModifierList)
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getObjectAttribute_Modifiers()
   * @model containment="true"
   * @generated
   */
  ModifierList getModifiers();

  /**
   * Sets the value of the '{@link tracerypp.traceryPlusPlus.ObjectAttribute#getModifiers <em>Modifiers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modifiers</em>' containment reference.
   * @see #getModifiers()
   * @generated
   */
  void setModifiers(ModifierList value);

} // ObjectAttribute
