/**
 * generated by Xtext 2.30.0
 */
package tracerypp.traceryPlusPlus;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Word List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tracerypp.traceryPlusPlus.WordList#getWords <em>Words</em>}</li>
 * </ul>
 *
 * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getWordList()
 * @model
 * @generated
 */
public interface WordList extends EObject
{
  /**
   * Returns the value of the '<em><b>Words</b></em>' containment reference list.
   * The list contents are of type {@link tracerypp.traceryPlusPlus.Word}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Words</em>' containment reference list.
   * @see tracerypp.traceryPlusPlus.TraceryPlusPlusPackage#getWordList_Words()
   * @model containment="true"
   * @generated
   */
  EList<Word> getWords();

} // WordList
