/*
 * generated by Xtext 2.29.0
 */
package uk.ac.kcl.inf.mdd.tracerypp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TraceryPPStandaloneSetup extends TraceryPPStandaloneSetupGenerated {

	public static void doSetup() {
		new TraceryPPStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
