grammar uk.ac.kcl.inf.mdd.tracerypp.TraceryPP with org.eclipse.xtext.common.Terminals


generate traceryPP "http://www.ac.uk/kcl/inf/mdd/tracerypp/TraceryPP"

Model:
	statements += Statement*
;
	
Statement:
	Rule
;

Rule:
	start_symbol = Variable  " can have values: " list = List
;

Variable:
	title = ID
;

List:
	word = Word (sep=Separator word = Word)*
;

Separator:
	"," | "or"
;

Word:
	word = STRING
;

